Feat/implement hud player zappy gui
FppEpitech/Zappy pull request #104
Opened 2024-06-11 14:16 UTC by mathieurobert1

> [!IMPORTANT]
> This pr must be merged after this issue : #81

I created the Hud for player and Game.
When it's free cam :
![image](https://github.com/FppEpitech/Zappy/assets/114564526/7e4cdc90-9b90-42aa-8458-913a2ed9fb5d)
And when its pov cam, the stats of the player are displayed.

2024-06-11 14:48 UTC, Thomaltarix approved these changes
Great !

2024-06-11 14:54 UTC, Njord201 requested changes
One request and try to make tests

2024-06-11 14:54 UTC, Njord201 commented on gui/include/Render/Render.hpp
> +        std::vector<std::shared_ptr<Gui::IHud>>      _hudList;           // List of huds.
Put this parameter with the other

2024-06-13 08:39 UTC, theophile-jr requested changes

2024-06-13 08:39 UTC, theophile-jr commented on gui/include/Hud/AHud.hpp
> +        std::shared_ptr<GameData>       _gameData;      // GameData class
.

2024-06-13 08:41 UTC, theophile-jr commented
merge w main

2024-06-13 15:18 UTC, theophile-jr approved these changes

2024-06-13 15:21 UTC, Njord201 requested changes
One request.. good luck :blush:

2024-06-13 15:21 UTC, Njord201 commented on gui/src/Hud/AHud.cpp
> +Gui::AHud::TypeScene Gui::AHud::getType()
Add const label

2024-06-13 15:24 UTC, Njord201 reviewed
All's good :+1:

2024-06-13 15:24 UTC, Njord201 submitted a review, later dismissed

2024-06-13 15:25 UTC, theophile-jr approved these changes

2024-06-13 15:27 UTC, theophile-jr approved these changes
LGTM

2024-06-13 15:27 UTC, Njord201 submitted a review, later dismissed
Great job mister Mathieu!

2024-06-13 15:28 UTC, Thomaltarix requested changes
Just some debug, overall it's a great job

2024-06-13 15:28 UTC, Thomaltarix commented on gui/src/Hud/HudGame.cpp
> +#include <iostream>
It might be debug

2024-06-13 15:28 UTC, Thomaltarix commented on gui/src/Hud/HudTile.cpp
> +#include <iostream>
Same i think, it might be debug

2024-06-13 15:33 UTC, Njord201 approved these changes

2024-06-13 15:33 UTC, Thomaltarix approved these changes
👍

2024-06-14 08:24 UTC, theophile-jr approved these changes

2024-06-14 08:24 UTC, merged