fix: python tests architecture
FppEpitech/Zappy pull request #109
Opened 2024-06-12 12:44 UTC by theophile-jr

2024-06-12 13:06 UTC, Njord201 submitted a review, later dismissed

2024-06-12 13:38 UTC, Marius-P1 requested changes
Good, just a small update about the dependencies and the coverage report

2024-06-12 13:38 UTC, Marius-P1 commented on ai/Makefile
> +	pipx run coverage report
I think you need to update the position of the .coveragerc to tests files and the executable from the coverage report

2024-06-13 08:37 UTC, Njord201 submitted a review, later dismissed

2024-06-13 09:33 UTC, mathieurobert1 submitted a review, later dismissed

2024-06-13 11:03 UTC, Marius-P1 approved these changes
👌

2024-06-13 11:13 UTC, Njord201 approved these changes

2024-06-13 11:13 UTC, mathieurobert1 approved these changes

2024-06-13 11:13 UTC, merged