feat (ci): chocolatine
FppEpitech/Zappy pull request #12
Opened 2024-05-24 16:36 UTC by Njord201

Adding of chocolatine with check_program_compilation, check_coding_style, run_tests and push_to_mirror rules.

2024-05-25 11:49 UTC, Thomaltarix commented on .github/workflows/mirror.yml
> +    - "ga-ignore-*"
Since pushes to main are blocked, all the code needs to come from pull-requests, so running the actions on pushes is just doubling each action for nothing :+1:

2024-05-25 11:49 UTC, Thomaltarix reviewed
A little comment for you before creating you pull-request :wink:

2024-05-26 15:05 UTC, mathieurobert1 approved these changes
Nice job.

2024-05-26 15:05 UTC, Thomaltarix requested changes
A little change for me

2024-05-26 15:05 UTC, Thomaltarix commented on .github/workflows/mirror.yml
> +  push:
As i said when your pull-request was a draft, it's better to only trigger the actions on pull-requests since any code can't go to main without coming from a pull-request. So you can just change `push` to `pull-request`

2024-05-26 15:05 UTC, Thomaltarix commented on .github/workflows/mirror.yml
> +  push:
And with this, the actions will be triggered for useless uses less times

2024-05-26 15:14 UTC, Thomaltarix commented on .github/workflows/mirror.yml
> +  push:
I'm wrong mb !

2024-05-26 15:18 UTC, Thomaltarix approved these changes
Great !

2024-05-26 15:21 UTC, mathieurobert1 approved these changes
Perfect :+1:

2024-05-26 15:21 UTC, merged