Feat/display cursor zappy gui
FppEpitech/Zappy pull request #123
Opened 2024-06-14 09:36 UTC by mathieurobert1

I display the cursor on the screen (that's all).

![image](https://github.com/FppEpitech/Zappy/assets/114564526/94e847dd-68c2-4fb9-bb0d-cb7ed9eba94d)

2024-06-14 11:26 UTC, theophile-jr submitted a review, later dismissed

2024-06-14 12:55 UTC, Thomaltarix requested changes
I think you shouln't be able to see the cursor when in 3rd (or 2nd when implemented) person

2024-06-17 08:16 UTC, theophile-jr approved these changes

2024-06-17 08:18 UTC, Thomaltarix approved these changes
:+1:

2024-06-17 08:18 UTC, merged