Feat/create interface to test network zappy gui
FppEpitech/Zappy pull request #180
Opened 2024-06-19 19:51 UTC by Thomaltarix

I refactored the `Network` class.
In fact, to test our program correctly, a network interface is compulsory.
This interface will make us able to develop a simple server that just redirect a standard file descriptor as the server, and then just write into this file descriptor.

To do so, i made a interface, and an abstract class `ANetwork` to simplify all the classes that will inherit from.

To see more details, check this issue: #161

2024-06-19 20:00 UTC, mathieurobert1 reviewed
:+1:  Seems good

2024-06-19 20:00 UTC, mathieurobert1 submitted a review, later dismissed

2024-06-20 07:40 UTC, theophile-jr commented
Requested myself following Thoma's request.

2024-06-20 07:44 UTC, theophile-jr submitted a review, later dismissed

2024-06-20 08:21 UTC, mathieurobert1 requested changes
Some space lags in private classes arguments.

2024-06-20 08:21 UTC, mathieurobert1 commented on gui/include/Engine/Engine.hpp
> +        std::shared_ptr<INetwork>    _network;       // Network class to connect to the server.
```suggestion
        std::shared_ptr<INetwork>   _network;       // Network class to connect to the server.
```

2024-06-20 08:21 UTC, mathieurobert1 commented on gui/include/GUIUpdater/GUIUpdater.hpp
> +        std::shared_ptr<INetwork>        _network; // The network to send commands to the server.
```suggestion
        std::shared_ptr<INetwork>       _network; // The network to send commands to the server.
```

2024-06-20 08:24 UTC, Thomaltarix commented on gui/include/Engine/Engine.hpp
> +        std::shared_ptr<INetwork>    _network;       // Network class to connect to the server.
Done

2024-06-20 08:54 UTC, mathieurobert1 approved these changes
Nice :+1:

2024-06-20 08:55 UTC, theophile-jr approved these changes
LGTM

2024-06-20 08:55 UTC, merged