Refactor/of the ai code and architecture zappy ai
FppEpitech/Zappy pull request #194
Opened 2024-06-20 12:26 UTC by theophile-jr

Fixed the merge with child-ai branch, put comments on all the missing functions, correctly merged marius & child ai functions. The refactor is lighter than we wanted.

2024-06-20 12:32 UTC, mathieurobert1 requested changes
Some requests but overall it's fine :+1:

2024-06-20 12:32 UTC, mathieurobert1 commented on ai/src/AI.py
>  import os
```suggestion
##

import os
```

2024-06-20 12:32 UTC, mathieurobert1 commented on ai/src/Player/Player.py
> +    def lookingForStones(self): #UP TO FIX YKYK
```suggestion
    def lookingForStones(self): 
```

2024-06-20 12:32 UTC, mathieurobert1 commented on ai/src/Player/Player.py
> +    def foodInVision(self, vision : list):
```suggestion
                self.take(itemSeek[i].value)

    def foodInVision(self, vision : list):
```

2024-06-20 12:32 UTC, mathieurobert1 commented on ai/src/Utils/Utils.py
> +def mapRangeOpti(n):
```suggestion
    return string

def mapRangeOpti(n):
```

2024-06-20 12:36 UTC, mathieurobert1 submitted a review, later dismissed
:+1:

2024-06-20 13:21 UTC, Marius-P1 requested changes
Some changes :+1:

2024-06-20 13:21 UTC, Marius-P1 commented on ai/src/Player/Player.py
> +    NONE = 9
There is a file with this code in src/enum/

2024-06-20 13:21 UTC, Marius-P1 commented on ai/src/Player/Player.py
> +from enum import Enum
Can be deleted since the enum is on another file

2024-06-20 13:21 UTC, Marius-P1 commented on ai/src/AI.py
> -
Don't remove the space, cause between all the function there is 2 new lines (or update for all the functions but the code will be more difficult to read)

2024-06-20 13:21 UTC, Marius-P1 commented on ai/src/Player/Player.py
> -
Don't remove the space, cause between all the function there is 2 new lines (or update for all the functions but the code will be more difficult to read)

2024-06-20 13:21 UTC, Marius-P1 commented on ai/src/Player/Player.py
> -
Don't remove the space, cause between all the function there is 2 new lines (or update for all the functions but the code will be more difficult to read)

2024-06-20 13:21 UTC, Marius-P1 commented on ai/src/Player/Player.py
> -
Don't remove the space, cause between all the function there is 2 new lines (or update for all the functions but the code will be more difficult to read)

2024-06-20 13:21 UTC, Marius-P1 commented on ai/src/Player/Player.py
> -
Don't remove the space, cause between all the function there is 2 new lines (or update for all the functions but the code will be more difficult to read)

2024-06-20 13:21 UTC, Marius-P1 commented on ai/src/Player/Player.py
> -
Don't remove the space, cause between all the function there is 2 new lines (or update for all the functions but the code will be more difficult to read)

2024-06-20 13:21 UTC, Marius-P1 commented on ai/src/Player/Player.py
> -
Don't remove the space, cause between all the function there is 2 new lines (or update for all the functions but the code will be more difficult to read)

2024-06-20 13:21 UTC, Marius-P1 commented on ai/src/Player/Player.py
> -
Don't remove the space, cause between all the function there is 2 new lines (or update for all the functions but the code will be more difficult to read)

2024-06-20 14:35 UTC, theophile-jr reviewed
Changes following marius's requests changes.

2024-06-20 15:23 UTC, Marius-P1 requested changes
Some little changes but overall is great :+1:

2024-06-20 15:23 UTC, Marius-P1 commented on ai/src/Player/Player.py
> +from ai.src.Enum.Item import Item
```suggestion
from ai.src.Enum.Item import Item
from ai.src.Enum.Action import Action
```

2024-06-20 15:23 UTC, Marius-P1 commented on ai/src/Player/Player.py
> +        for i, v in map:
Why don't you use the same method as line 882 (using mapRangeOpti) ?

2024-06-20 15:23 UTC, Marius-P1 commented on ai/src/Player/Player.py
> +        return (False, -1, None)
Here you take stones from the nearest case where stones are present but not from the case where there is the more diversity of stone like i was doing in looking for stones. So maybe you can update that so the AI will be able to catch different stones (more diversity = more chance to take the stone we needed)

2024-06-20 15:23 UTC, Marius-P1 commented on ai/src/Player/Player.py
Can you put your method on top or behind the method they are use (like lookingForFood) so it won't break the reasoning order i have done for the choose action ?

2024-06-20 15:23 UTC, Marius-P1 commented on ai/src/Utils/Utils.py
> +
```suggestion


```

2024-06-20 15:23 UTC, Marius-P1 commented on ai/src/Utils/Utils.py
> +
```suggestion


```

2024-06-20 15:26 UTC, theophile-jr commented on ai/src/Player/Player.py
> +        for i, v in map:
because this is an enumerate (rendering a list of tuple) and not a range ;)

2024-06-20 17:49 UTC, mathieurobert1 approved these changes

2024-06-21 18:04 UTC, mathieurobert1 approved these changes

2024-06-22 15:05 UTC, Marius-P1 requested changes
Two little change but the overall is great

2024-06-22 15:05 UTC, Marius-P1 commented on .gitkeep
Why ?

2024-06-22 15:05 UTC, Marius-P1 commented on ai/src/Player/Player.py
> +    def goGetItem(self, index, itemSeek : List[Item]):
if you write the type of one param, write the type of the other too

2024-06-22 17:41 UTC, theophile-jr commented on .gitkeep
mistake, removed

2024-06-22 17:44 UTC, mathieurobert1 approved these changes
If @Marius-P1 accept, it's ok.

2024-06-22 19:05 UTC, Marius-P1 submitted a review, later dismissed

2024-06-22 20:06 UTC, mathieurobert1 approved these changes

2024-06-22 20:07 UTC, Marius-P1 commented on ai/src/Player/Player.py
> +import random
double import
```suggestion
```

2024-06-22 20:09 UTC, Marius-P1 approved these changes
:ok:

2024-06-22 20:11 UTC, mathieurobert1 approved these changes

2024-06-22 20:13 UTC, merged