Fix/bug a label level title appears in the gui at the opposite of camera and robot zappy gui
FppEpitech/Zappy pull request #201
Opened 2024-06-20 15:22 UTC by Thomaltarix

I fixed the size of the text broadcast and level font.

The fix of the level that appears in the gui at the opposite of the camera is not done yet

2024-06-20 15:23 UTC, Njord201 submitted a review, later dismissed

2024-06-21 14:17 UTC, Njord201 commented on gui/src/Render/Render.cpp
> +
Remove one line no ?

2024-06-21 14:18 UTC, Thomaltarix commented on gui/src/Render/Render.cpp
> +
In fact !

2024-06-21 14:19 UTC, Njord201 submitted a review, later dismissed

2024-06-21 14:27 UTC, Njord201 approved these changes

2024-06-21 14:27 UTC, mathieurobert1 requested changes
Just a simple update in documentation

2024-06-21 14:27 UTC, mathieurobert1 commented on gui/include/Render/Render.hpp
> +        void displayPlayerLevel(Player &player, Vector3 position, Team &team);
Update doxygen param

2024-06-21 14:29 UTC, Thomaltarix commented on gui/include/Render/Render.hpp
> +        void displayPlayerLevel(Player &player, Vector3 position, Team &team);
Done

2024-06-21 14:31 UTC, Njord201 approved these changes

2024-06-21 14:32 UTC, mathieurobert1 approved these changes
Nice work !

2024-06-21 14:33 UTC, merged