Create a smart select it must be blocking if necessary and over a good period of time zappy server
FppEpitech/Zappy pull request #202
Opened 2024-06-20 15:29 UTC by Njord201

I've added a smart select, the timeout of select if based on the frequency

2024-06-20 15:54 UTC, Thomaltarix submitted a review, later dismissed

2024-06-20 15:59 UTC, mathieurobert1 approved these changes
:+1:

2024-06-21 14:17 UTC, Thomaltarix requested changes
Some little changes, but overall great

2024-06-21 14:17 UTC, Thomaltarix commented on server/src/server/run.c
> +    }
Useless brackets here

2024-06-21 14:17 UTC, Thomaltarix commented on server/src/server/run.c
> +    timeout_final.tv_usec = timeout * 1000000;
Maybe the 1000000 may be a define since you are using it many times in this file

2024-06-21 14:17 UTC, Thomaltarix commented on server/src/server/run.c
> +        (end.tv_nsec - start->tv_nsec) / 1000000;
Same Here

2024-06-21 14:17 UTC, Thomaltarix commented on server/src/server/run.c
> +        if (timeout.tv_usec == 1000000)
Same here

2024-06-21 14:29 UTC, AxelF44 requested changes
That's doesn't work !

Please test it !
Try to launch server, after with another terminal launch netcat: "nc 127.0.0.1 port".
After try a command like Forward, Right or even Left just a simple command.
And tell me if you see a respond of the server.

2024-06-22 09:00 UTC, mathieurobert1 requested changes

2024-06-22 09:00 UTC, mathieurobert1 commented on server/src/server/server.c
> +#include <sys/time.h>
For what ?

2024-06-22 20:15 UTC, mathieurobert1 approved these changes

2024-06-22 21:59 UTC, Thomaltarix submitted a review, later dismissed

2024-06-23 10:47 UTC, AxelF44 submitted a review, later dismissed

2024-06-23 10:50 UTC, mathieurobert1 approved these changes
Nice

2024-06-23 10:57 UTC, AxelF44 approved these changes

2024-06-23 11:00 UTC, mathieurobert1 approved these changes
Seems correct

2024-06-23 11:19 UTC, Thomaltarix approved these changes

2024-06-23 11:20 UTC, merged