Feat/display only players vision zappy gui
FppEpitech/Zappy pull request #236
Opened 2024-06-21 16:59 UTC by Thomaltarix

I added the possibility to see only the player's view.

Here's the normal view:

![image](https://github.com/FppEpitech/Zappy/assets/114673563/85a8f754-e2d8-4eb5-ae13-0481f34ffa33)

And here's the player's view:

![image](https://github.com/FppEpitech/Zappy/assets/114673563/adb21abd-7b52-4452-80e1-aa7c57e9985a)

> [!Warning]
> At the moment, the only missing thing is the positions that the player can see

2024-06-21 18:58 UTC, Njord201 requested changes

2024-06-21 18:58 UTC, Njord201 commented on gui/include/Render/Render.hpp
> +         * @note True to display player vision
```suggestion
         * @note True to display player vision.
```

2024-06-21 18:58 UTC, Njord201 commented on gui/src/Event/Event.cpp
> +    _render.get()->setPlayerVision(!_render.get()->getPlayerVision());
You can't do this ? (With an arrow)

```suggestion
    _render->get()->setPlayerVision(!_render.get()->getPlayerVision());
```

2024-06-21 18:58 UTC, Njord201 commented on gui/src/Render/Render.cpp
> +                std::cout << "Error: Invalid orientation" << std::endl;
Why not std::cerr?

2024-06-21 19:00 UTC, Thomaltarix commented on gui/src/Render/Render.cpp
> +                std::cout << "Error: Invalid orientation" << std::endl;
Mb it's debug ahahah

2024-06-21 19:02 UTC, Thomaltarix commented on gui/src/Event/Event.cpp
> +    _render.get()->setPlayerVision(!_render.get()->getPlayerVision());
Because here, `_render` is the variable, to get the pointer itself, you do .get(), then (as already written), you can use the arrow to call you methods, etc...

2024-06-21 19:03 UTC, Thomaltarix commented on gui/include/Render/Render.hpp
> +         * @note True to display player vision
Done

2024-06-21 19:09 UTC, Njord201 approved these changes

2024-06-22 08:49 UTC, mathieurobert1 submitted a review, later dismissed
Beautiful !

2024-06-22 12:29 UTC, mathieurobert1 approved these changes

2024-06-22 13:32 UTC, Njord201 approved these changes

2024-06-22 14:09 UTC, merged