Implemente system of list : ZAPPY Server
FppEpitech/Zappy pull request #24
Opened 2024-06-01 16:58 UTC by AxelF44

I've implemented the list system for the server !

2024-06-01 17:05 UTC, mathieurobert1 requested changes
Some doxygen errors. Moreover, we can discuss about return types.

2024-06-01 17:05 UTC, mathieurobert1 commented on server/include/list/list.h
> + * @brief Remove the first note of the list.
```suggestion
 * @brief Remove the first node of the list.
```

2024-06-01 17:05 UTC, mathieurobert1 commented on server/include/list/list.h
> + * @brief Remove the last note of the list.
```suggestion
 * @brief Remove the last node of the list.
```

2024-06-01 17:05 UTC, mathieurobert1 commented on server/include/list/list.h
> + * @return int 0 if succes else 84
Why not a bool type ?

2024-06-01 17:05 UTC, mathieurobert1 commented on server/include/list/list.h
> + * @return int 0 if succes else 84
Why not a bool type ?

2024-06-02 10:12 UTC, mathieurobert1 submitted a review, later dismissed
Perfect, just the chocolatine to fix.

2024-06-02 11:34 UTC, mathieurobert1 approved these changes
Nice good job for the tests !

2024-06-02 14:58 UTC, Thomaltarix approved these changes

2024-06-02 16:25 UTC, Njord201 approved these changes

2024-06-02 16:25 UTC, merged