Implement connection and responde on server
FppEpitech/Zappy pull request #52
Opened 2024-06-05 09:35 UTC by AxelF44

I've implemented the arrival of Client, Ai and GUI.

That's include of course the system of communication (write and read) with them.

2024-06-05 21:55 UTC, mathieurobert1 requested changes
Overall that's a great work !

2024-06-05 21:55 UTC, mathieurobert1 commented on server/include/server/client.h
> + * @param fd File descriptor of ai
```suggestion
 * @param fd File descriptor of ai.
```

2024-06-05 21:55 UTC, mathieurobert1 commented on server/include/server/client.h
> + * @return client_t* Struct client initialized
```suggestion
 * @return client_t* Struct client initialized.
```

2024-06-05 21:55 UTC, mathieurobert1 commented on server/include/server/server.h
Be careful to some points at the end of doxygen sentences.

2024-06-05 21:55 UTC, mathieurobert1 commented on server/src/server/read/read_data.c
> +    char *line = malloc(sizeof(char) * 1);
check your malloc

2024-06-05 21:55 UTC, mathieurobert1 commented on server/src/server/read/read_data.c
> +    line = realloc(line, len_line + 2);
I'm not sure but you have to check realloc ?

2024-06-06 08:05 UTC, Njord201 commented on server/src/server/read/read_data.c
> +    line = realloc(line, len_line + 2);
Check it

2024-06-06 08:07 UTC, Njord201 commented on server/include/ai/ai.h
> +** AI struct
The file description is false.

2024-06-06 08:09 UTC, Njord201 commented on server/include/ai/team.h
> + * @param max_place Max place in a team
Don't forget the point.


```suggestion
 * @param max_place Max place in a team.
```

2024-06-06 08:09 UTC, Njord201 commented on server/include/ai/ai.h
> + * @param team Team of AI
Don't forget the point at the end of the sentence.


```suggestion
 * @param team Team of AI.
```

2024-06-06 08:10 UTC, Njord201 commented on server/include/app/app.h
> +** App struct
The file description is false, not only the structure.

2024-06-06 08:11 UTC, Njord201 commented on server/include/gui/gui.h
Don't forget the point in the functions descriptions.

2024-06-06 08:12 UTC, Njord201 commented on server/include/list/type.h
Maybe rename the file in types.h

2024-06-06 08:14 UTC, Njord201 commented on server/src/ai/ai.c
> +        }
Useless brackets

2024-06-06 08:14 UTC, Njord201 commented on server/src/app/app.c
> +    }
Useless brackets

2024-06-06 08:16 UTC, Njord201 commented on server/src/gui/gui.c
> +        }
Useless brackets

2024-06-06 08:16 UTC, Njord201 commented on server/src/server/read/connection.c
> +    printf("NEW CONNECTION !\n");
Print in the stderr no ?

2024-06-06 08:18 UTC, Njord201 commented on server/src/server/read/connection.c
> +    write(client_fd, "WELCOME\n", strlen("WELCOME\n"));
Maybe put the string in a macro? One for the connection message and one for the length of the connection message?

2024-06-06 08:21 UTC, Njord201 commented on server/src/server/read/read_data.c
> +    ssize_t bytes_received;
I don't think you need this variable (bytes_received), first of all you can only receive one byte in this configuration and you can put the read in if and while.

2024-06-06 08:22 UTC, Njord201 commented on server/src/server/read/read_data.c
> +void handle_request(app_t *app, size_t fd, char *line)
Why do you need the line variable?

2024-06-06 08:25 UTC, Njord201 commented on server/src/server/read/read_data.c
> +{
This function is weird is it finished?

2024-06-06 08:26 UTC, Njord201 commented on server/src/server/read/read_data.c
> +        }
Useless brackets

2024-06-06 08:30 UTC, Njord201 commented on server/src/server/run.c
> +        }
Useless

2024-06-06 08:30 UTC, Njord201 commented on server/src/server/run.c
> +    }
Useless brackets

2024-06-06 13:03 UTC, mathieurobert1 approved these changes
Seems done :+1:

2024-06-06 14:26 UTC, Njord201 requested changes
Some little request, good job !

2024-06-06 14:26 UTC, Njord201 commented on server/include/server/server.h
Some points are missing with doxygen

2024-06-06 14:26 UTC, Njord201 commented on server/src/ai/ai.c
> +bool add_ia(app_t *app, size_t fd, char *line)
If you return true in all cases, why not define the function type as void?

2024-06-06 14:26 UTC, Njord201 commented on server/src/app/app.c
> +
Remove this useless line

2024-06-06 14:26 UTC, Njord201 commented on server/src/gui/gui.c
> +bool add_gui(app_t *app, size_t fd)
Same here, you can change the return type of the function to void

2024-06-06 14:26 UTC, Njord201 commented on server/src/server/run.c
> +int handle_client_read(app_t *app, int fd)
You can put the return type of the function in void.

2024-06-06 14:26 UTC, Njord201 commented on server/src/server/run.c
> +int handle_client_write(app_t *app, int fd)
You can put the return type of the function in void.

2024-06-06 14:42 UTC, Njord201 approved these changes
Good job

2024-06-06 15:06 UTC, mathieurobert1 approved these changes

2024-06-06 15:07 UTC, merged