Feat/display food and resources zappy gui
FppEpitech/Zappy pull request #56
Opened 2024-06-05 15:54 UTC by mathieurobert1

I displayed food and the different resources on tile :
![image](https://github.com/FppEpitech/Zappy/assets/114564526/d3d4f729-a693-4154-9dd8-72a342e2081d)

2024-06-05 15:56 UTC, Njord201 requested changes

2024-06-05 15:56 UTC, Njord201 commented on gui/include/Render/Render.hpp
> +        bool                        _isDebug;           // Display or not the debug informations.
Add a point at the end of the sentence

2024-06-05 15:59 UTC, Njord201 requested changes

2024-06-05 15:59 UTC, Njord201 commented on gui/src/Render/Render.cpp
> +void Gui::Render::displayFood(Tile tile)
```suggestion
void Gui::Render::displayFood(Tile tile) const
```

2024-06-05 15:59 UTC, Njord201 commented on gui/src/Render/Render.cpp
> +void Gui::Render::displayResources(Tile tile)
```suggestion
void Gui::Render::displayResources(Tile tile) const
```

2024-06-05 15:59 UTC, Njord201 commented on gui/src/Render/Render.cpp
> +void Gui::Render::displayLinemate(Tile tile)
```suggestion
void Gui::Render::displayLinemate(Tile tile) const
```

2024-06-05 15:59 UTC, Njord201 commented on gui/src/Render/Render.cpp
> +void Gui::Render::displayMendiane(Tile tile)
```suggestion
void Gui::Render::displayMendiane(Tile tile) const
```

2024-06-05 15:59 UTC, Njord201 commented on gui/src/Render/Render.cpp
> +void Gui::Render::displayPhiras(Tile tile)
```suggestion
void Gui::Render::displayPhiras(Tile tile) const
```

2024-06-05 15:59 UTC, Njord201 commented on gui/src/Render/Render.cpp
> +void Gui::Render::displaySibur(Tile tile)
```suggestion
void Gui::Render::displaySibur(Tile tile) const
```

2024-06-05 15:59 UTC, Njord201 commented on gui/src/Render/Render.cpp
> +void Gui::Render::displayThystame(Tile tile)
```suggestion
void Gui::Render::displayThystame(Tile tile) const
```

2024-06-05 15:59 UTC, Njord201 commented on gui/src/Render/Render.cpp
> +void Gui::Render::displayDeraumere(Tile tile)
```suggestion
void Gui::Render::displayDeraumere(Tile tile) const
```

2024-06-05 16:02 UTC, Njord201 submitted a review, later dismissed

2024-06-05 16:26 UTC, theophile-jr submitted a review, later dismissed

2024-06-05 16:26 UTC, theophile-jr commented on gui/include/Assets.hpp
> +#define MODEL_FOOD                  "assets/food.glb"
"PATH_"...

2024-06-05 16:42 UTC, Thomaltarix approved these changes
Clean one

2024-06-05 16:46 UTC, theophile-jr approved these changes

2024-06-05 16:47 UTC, Njord201 approved these changes

2024-06-05 16:48 UTC, merged

2024-06-11 14:56 UTC, theophile-jr commented
Change assets :))