Feat/implement the update of the gamedata class zappy gui
FppEpitech/Zappy pull request #59
Opened 2024-06-05 17:26 UTC by Thomaltarix

I partially implemented the update of the GameData thanks to the server parsing.

At the moment, i have all this commands done:
![image](https://github.com/FppEpitech/Zappy/assets/114673563/53fa4a03-a175-4b9a-9c5f-2149bc221f76)

There's approximately half of the commands to do, but since the base of the methods are the same, i'm building this draft.

Too see more details, check this issue: #47

2024-06-05 17:55 UTC, mathieurobert1 approved these changes

2024-06-05 17:56 UTC, mathieurobert1 requested changes
The tests_run failed

2024-06-05 18:02 UTC, Njord201 reviewed
Too much useless bracket, it's ok if you write them everytime but it's not the case in your code. So delete them or write them everytime. :-1:

2024-06-05 18:02 UTC, Njord201 commented on gui/src/GUIUpdater/GUIUpdater.cpp
> +    }
Same

2024-06-05 18:02 UTC, Njord201 commented on gui/src/GUIUpdater/GUIUpdater.cpp
> +}
Same

2024-06-05 18:02 UTC, Njord201 commented on gui/src/GUIUpdater/GUIUpdater.cpp
> +    }
Same for try  catch

2024-06-05 19:36 UTC, Thomaltarix commented on gui/include/GUIUpdater/GUIUpdater.hpp
Done

2024-06-05 19:37 UTC, Thomaltarix commented on gui/src/GUIUpdater/GUIUpdater.cpp
> +    for (auto &team : _gameData->getTeams()) {
Done

2024-06-05 19:37 UTC, Thomaltarix commented on gui/src/GUIUpdater/GUIUpdater.cpp
> +        }
Done

2024-06-05 19:38 UTC, Thomaltarix commented on gui/src/GUIUpdater/GUIUpdater.cpp
> +    }
No, those are compulsory

2024-06-05 19:38 UTC, Thomaltarix commented on gui/src/GUIUpdater/GUIUpdater.cpp
> +    try {
Compulsory too

2024-06-05 19:38 UTC, Thomaltarix commented on gui/src/GUIUpdater/GUIUpdater.cpp
> +    try {
Same

2024-06-05 19:39 UTC, Thomaltarix commented on gui/src/GUIUpdater/GUIUpdater.cpp
> +    } catch (const std::exception &error) {
Same

2024-06-05 19:39 UTC, Thomaltarix commented on gui/src/GUIUpdater/GUIUpdater.cpp
> +    }
Done

2024-06-05 19:39 UTC, Thomaltarix commented on gui/src/GUIUpdater/GUIUpdater.cpp
> +}
Same

2024-06-05 19:39 UTC, Thomaltarix commented on gui/src/GUIUpdater/GUIUpdater.cpp
> +    }
Same

2024-06-05 20:14 UTC, mathieurobert1 reviewed
Nice but why some tests are commented ?

2024-06-05 20:14 UTC, mathieurobert1 commented on gui/tests/GUIUpdater/TestGUIUpdater.cpp
> +    // guiUpdater.update("bct", {"1", "1", "1", "1", "1", "1", "1", "1", "1"});
Why is this commented ?

2024-06-05 20:14 UTC, mathieurobert1 commented on gui/tests/GUIUpdater/TestGUIUpdater.cpp
> +// Test(GUIUpdater, updateTeamMemberError, .timeout = 5)
Why is this commented ?

2024-06-05 20:46 UTC, Thomaltarix commented on gui/tests/GUIUpdater/TestGUIUpdater.cpp
> +    // guiUpdater.update("bct", {"1", "1", "1", "1", "1", "1", "1", "1", "1"});
Because the `bct` command is not finished, so that the tests can pass, and you can review :wink:

2024-06-05 20:46 UTC, Thomaltarix commented on gui/tests/GUIUpdater/TestGUIUpdater.cpp
> +// Test(GUIUpdater, updateTeamMemberError, .timeout = 5)
Because the `pnw` command is not finished, so that the tests can pass, and you can review :wink:

2024-06-05 20:54 UTC, mathieurobert1 submitted a review, later dismissed

2024-06-06 08:00 UTC, mathieurobert1 submitted a review, later dismissed
Nice work !

2024-06-06 08:02 UTC, Njord201 commented on gui/src/GameDatas/Inventory.cpp
Add const labels when it's possible

2024-06-06 08:04 UTC, Njord201 requested changes
Some little changes

2024-06-06 12:28 UTC, Thomaltarix commented on gui/src/GameDatas/Inventory.cpp
I tried, but since it quite always references, the `const` can't be applied

2024-06-06 12:32 UTC, mathieurobert1 approved these changes
Nice.

2024-06-06 13:29 UTC, Njord201 approved these changes

2024-06-06 14:05 UTC, merged