feat: Create a API class for the AI
FppEpitech/Zappy pull request #61
Opened 2024-06-05 21:40 UTC by Marius-P1

I've added the basic API to connect the AI to our server and the first exchange (see below).

For now, I've linked the API to the main to let you see how the API works, but it will be put into an AI class in the future.

:exclamation: Feel free to give your opinion on how I documented each function.

![image](https://github.com/FppEpitech/Zappy/assets/114705049/9696b64b-6522-43e0-ac1e-d8d41b9d3711)

2024-06-05 21:50 UTC, Thomaltarix requested changes
A little request and a advice, but overall it's a great job

2024-06-05 21:50 UTC, Thomaltarix commented on ai/src/main.py
For me, you should print the error messages in the error output :+1:

2024-06-05 21:50 UTC, Thomaltarix commented on ai/src/network/API.py
You can build your own Exception classes to be more accurate in your errors :+1:  (like in c++)

2024-06-05 22:00 UTC, mathieurobert1 approved these changes
Seems good :+1:

2024-06-06 07:48 UTC, Njord201 submitted a review, later dismissed

2024-06-06 12:59 UTC, AxelF44 submitted a review, later dismissed

2024-06-07 14:33 UTC, Marius-P1 commented
I added some tests _(before you ask API is complicated to test because it's about the connection between the AI and the server)_

:warning: For the moment you can't have the coverage rapport (like behind) without using a virtual env and the required dependencies, i will make a script later and a readme that explain everything (but i don't think that the priority for the moment and i can evolve in the futur so it's rather useless at this moment to do one)

Coverage :
![image](https://github.com/FppEpitech/Zappy/assets/114705049/463ea116-54f4-486a-ad64-3c824aa133a3)

2024-06-07 14:54 UTC, Thomaltarix approved these changes
Clean ! But don't forget to make a README.md for the tests when it will be implemented :+1:

2024-06-07 15:26 UTC, theophile-jr commented
Don't forget to follow branches name convention ;) SEEMS GOOD !

2024-06-07 16:33 UTC, mathieurobert1 approved these changes
Seems good :+1:

2024-06-07 17:20 UTC, merged