feat: structs for server entities
FppEpitech/Zappy pull request #62
Opened 2024-06-06 07:43 UTC by theophile-jr

2024-06-06 16:37 UTC, Njord201 approved these changes

2024-06-06 18:19 UTC, AxelF44 requested changes

2024-06-06 18:19 UTC, AxelF44 commented on server/include/map/map.h
> +* @return tile_t***
Document your parameters

2024-06-06 18:19 UTC, AxelF44 commented on server/include/map/map.h
> +* @param width
Document your parameters

2024-06-06 18:19 UTC, AxelF44 commented on server/include/map/map.h
> +* @param width
Document your parameters

2024-06-06 18:19 UTC, AxelF44 commented on server/src/main.c
> +#include "map/map.h"
Put your include in ascending order

2024-06-07 08:19 UTC, mathieurobert1 requested changes
Be careful, check your mallocs.

2024-06-07 08:19 UTC, mathieurobert1 commented on server/src/map/map.c
> +    tile_t ***map = malloc(sizeof(tile_t **) * height);
check your malloc

2024-06-07 08:19 UTC, mathieurobert1 commented on server/src/map/map.c
> +        map[i] = malloc(sizeof(tile_t *) * width);
Check your malloc

2024-06-07 08:19 UTC, mathieurobert1 commented on server/src/map/map.c
> +            map[i][j] = malloc(sizeof(tile_t));
check your malloc

2024-06-07 09:04 UTC, AxelF44 approved these changes

2024-06-07 09:09 UTC, Njord201 approved these changes

2024-06-07 09:15 UTC, mathieurobert1 approved these changes
Nice job

2024-06-07 09:21 UTC, merged