Feat/display players zappy gui
FppEpitech/Zappy pull request #63
Opened 2024-06-06 08:25 UTC by mathieurobert1

>WARNING
> This pr must be merge after this one : #59 

I displayed players based on there team skin:
![image](https://github.com/FppEpitech/Zappy/assets/114564526/7cb38ce4-a0e4-4e24-ad5a-7c6d069aaa34)

2024-06-06 14:13 UTC, Njord201 reviewed
It's ok for me, just why you remove the tests files ?

2024-06-06 14:13 UTC, Njord201 commented on gui/include/GameDatas/Team.hpp
> +        Team(const std::string &name, const std::string &modelPath);
Describe the param added

2024-06-06 14:13 UTC, Njord201 commented on gui/src/GameDatas/Team.cpp
> +Model Gui::Team::getModel(void)
Add const label

2024-06-06 14:14 UTC, Njord201 requested changes
Do previous request, mb

2024-06-06 15:07 UTC, Thomaltarix approved these changes
Clean one, just check the kylian's requests

2024-06-07 07:40 UTC, Thomaltarix requested changes
I mainly requested the name you're using for the Player model / model path

2024-06-07 07:40 UTC, Thomaltarix commented on gui/include/GameDatas/GameData.hpp
> +        void addTeam(const std::string &name, const std::string &modelPath);
Since i'll add the egg model too, you should rename it `playerModelPath` i think

2024-06-07 07:40 UTC, Thomaltarix commented on gui/include/GameDatas/Team.hpp
> +        Team(const std::string &name, const std::string &modelPath);
Same there, you should rename the parameter `playerModelPath`

2024-06-07 07:40 UTC, Thomaltarix commented on gui/include/GameDatas/Team.hpp
> +        Model getModel(void);
Same here for `getPlayerModel`

2024-06-07 07:40 UTC, Thomaltarix commented on gui/src/GameDatas/Team.cpp
> +    _model = LoadModel(modelPath.c_str());
Same here, you should write `_playerModel` instead of just `_model` since there's the egg too

2024-06-07 07:40 UTC, Thomaltarix commented on gui/src/GameDatas/GameData.cpp
> +void Gui::GameData::addTeam(const std::string &name, const std::string &modelPath)
Same here for the name of the variable

2024-06-07 07:40 UTC, Thomaltarix commented on gui/include/GameDatas/Team.hpp
> +        Model                       _model;     // Model asset of the team.
Same here for the name of the variable

2024-06-07 08:14 UTC, Thomaltarix approved these changes

2024-06-07 08:28 UTC, Njord201 approved these changes

2024-06-07 08:31 UTC, merged