Feat/implement parsing of gui commands
FppEpitech/Zappy pull request #93
Opened 2024-06-11 08:06 UTC by Njord201

2024-06-12 09:21 UTC, mathieurobert1 requested changes
A unique request

2024-06-12 09:21 UTC, mathieurobert1 commented on server/src/gui/communication/pin.c
> +static bool is_str_number(char *str)
you repeat this function in many file, please make an util file.

2024-06-13 11:12 UTC, theophile-jr requested changes
request changes + talked w njord IRL about some issues.

2024-06-13 11:12 UTC, theophile-jr commented on server/src/gui/communication/pgt.c
> +    for (int i = 0; i < 7; i++) {
MACRO

2024-06-13 11:12 UTC, theophile-jr commented on server/src/gui/communication/ppo.c
> +    if (line[3] != ' ') {
MACRO // same for other files.

2024-06-13 11:12 UTC, theophile-jr commented on server/src/gui/communication/sst.c
> +    line += 4;
//

2024-06-17 11:52 UTC, Thomaltarix requested changes
Some changes to request, but overall great

2024-06-17 11:52 UTC, Thomaltarix commented on server/include/gui/communication.h
> +#include "gui.h"
Wrong include order

2024-06-17 11:52 UTC, Thomaltarix commented on server/src/gui/communication/sst.c
> +// TODO error
I think you can precise what's needed

2024-06-17 11:52 UTC, Thomaltarix commented on server/src/app/app.c
>      || new_app->teams_list == NULL)
You're adding a malloc but not adding its verification ?

2024-06-17 11:52 UTC, Thomaltarix commented on server/src/gui/communication/loop.c
> +};
For me, since its something constant, that doesn't change, it should be in a header file

2024-06-17 12:14 UTC, mathieurobert1 requested changes
Some requests.

2024-06-17 12:14 UTC, mathieurobert1 commented on server/src/app/app.c
> +    new_app->eggs_list = malloc(sizeof(list_t));
check your malloc

2024-06-18 08:46 UTC, mathieurobert1 submitted a review, later dismissed
Seems good, hope @AxelF44 tests will be approved.

2024-06-18 09:02 UTC, AxelF44 requested changes

2024-06-18 09:02 UTC, AxelF44 commented on server/src/server/read/read_data.c
> +            return;
Remove this it's useless.

2024-06-18 14:04 UTC, AxelF44 requested changes

2024-06-18 14:04 UTC, AxelF44 commented on server/src/ai/ai.c
> +            free(temp->data.team->eggs_list->first->data.egg);
You free the egg struct but not the struct vector_i !

2024-06-18 14:04 UTC, theophile-jr approved these changes

2024-06-18 14:06 UTC, mathieurobert1 approved these changes
Seems good

2024-06-18 14:14 UTC, AxelF44 approved these changes

2024-06-18 14:14 UTC, mathieurobert1 approved these changes
Nice :+1:

2024-06-18 14:51 UTC, theophile-jr approved these changes

2024-06-18 15:20 UTC, Thomaltarix approved these changes

2024-06-18 15:20 UTC, merged